services:
  db:
    image: postgres:alpine
    container_name: postgres-fuel-go
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - fuel_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-fuel-go
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    networks:
      - fuel_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fuel_network:
    driver: bridge
